# Generated by Django 3.2.25 on 2024-06-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='user',
        ),
    ]
