# Generated by Django 3.2.8 on 2024-06-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='watch_data',
            new_name='watch_date',
        ),
    ]
